services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  produtor:
    build: ./produtor-rabbit
    container_name: produtor-rabbit
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumidor:
    build: ./consumidor-rabbit
    container_name: consumidor-rabbit
    depends_on:
      rabbitmq:
        condition: service_healthy